---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  # Community Roles from Ansible Galaxy
  roles:
    - role: custom/default
    - role: PeterMosmans.virtualbox-guest
      become: true
    # - role: gotmax23.zoom