---
- hosts: all

  vars_files:
    - config.yml
  
  # pre_tasks:
  #   - name: Include playbook configuration.
  #     include_vars: "{{ item }}"
  #     loop:
  #       - config.yml
  #     tags: ['always']
  #     ignore_errors: true

  # Community Roles from Ansible Galaxy
  roles:
    # - role: custom/default
    # - role: PeterMosmans.virtualbox-guest
    #   become: true
    # - role: Gotmax23.zoom
    #   become: true
    - role: Iesplin.Burpsuite
      become: true