---
roles:
  - src: https://github.com/carefreecaribou/ansible-role-virtualbox-guest
    scm: git
    name: PeterMosmans.virtualbox-guest
  - src: https://github.com/carefreecaribou/ansible-role-zoom/
    version: check-zoom-installed
    scm: git
    name: Gotmax23.zoom
collections:
  - name: community.docker
  - name: community.general