---
roles:
  - src: https://github.com/PeterMosmans/ansible-role-virtualbox-guest
    scm: git
    name: PeterMosmans.virtualbox-guest
  - src: https://github.com/gotmax23/ansible-role-zoom
    scm: git
    name: gotmax23.zoom
collections:
  - name: community.docker
  # - name: community.general