---
# Enable Banner Message
- name: Enable Banner Message
  replace: 
    path: /etc/gdm3/greeter.dconf-defaults
    regexp: '^#( banner-message-enable=true).*$'
    replace: \1
  become: true

# Insert Banner Message
- name: Insert Banner Message
  replace: 
    path: /etc/gdm3/greeter.dconf-defaults
    regexp: ^#( banner-message-text=\').*?\'.*$
    replace: \1{{ banner_message }}'
  become: true

# Install Customization Package Requirements
- name: Install Customization packages with apt.
  apt:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ customization_packages }}"
  become: true

# Start TLP
- name: Start TLP
  systemd:
    name: tlp
    state: started
    enabled: true
  become: true

# Disable Bluetooth From Autostarting on Boot
- name: Disable Bluetooth from autostarting on boot
  replace: 
    path: /etc/tlp.conf
    regexp: ^#?(DEVICES_TO_DISABLE_ON_STARTUP=")bluetooth nfc wifi wwan".*$
    replace: \1{{ devices_to_disable }}"
  become: true