---
- name: get the username running the deploy
  become: false
  action: command whoami
  register: host_user
  listen: wireshark_get_user

- name: Add current user to wireshark group.
  user:
    name: "{{ host_user }}"
    append: true
    groups: wireshark
  become: true
  listen: add_wireshark_as_nonsudo

- name: Remove current user to wireshark group.
  user:
    name: "{{ host_user }}"
    remove: true
    groups: wireshark
  become: true
  listen: remove_wireshark_as_nonsudo

- name: Set the fact to notify user group.
  set_fact: user_group_changed = true